name: Cypress Tests

on: [push]

jobs:
  cypress-ren:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with: 
          build: npm i server
          start:  serve app -p 8080
        
        
